---
language: ruby
rvm:
  - 3.0.0
  - 3.1.2
gemfile:
  - gemfiles/rails_6.gemfile
  - gemfiles/rails_7.gemfile
env:
  - GENEALOGY_TEST_DB=mysql
  - GENEALOGY_TEST_DB=postgres
matrix:
  fast_finish: true
before_script:
  - mysql -e 'create database genealogy_test;'
  - psql -c 'create database genealogy_test;' -U postgres
