sqlite:
  adapter: sqlite3
  database: spec/test.sqlite3.db

mysql:
  adapter: mysql2
  encoding: utf8
  database: genealogy_test
  username: root

# mysql:
#   adapter: mysql2
#   encoding: utf8
#   reconnect: false
#   database: genealogy_test
#   pool: 5
#   username: root
#   password:
#   socket: /tmp/mysql.sock
